# Generated by Django 5.1.2 on 2024-10-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="continent",
            field=models.CharField(
                choices=[
                    ("asia", "Asia"),
                    ("europe", "Europe"),
                    ("middleEast ", "Middle East"),
                ],
                default="europe",
                max_length=250,
            ),
        ),
    ]
