# Generated by Django 5.1.2 on 2024-10-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0002_alter_country_continent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="continent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("asia", "Asia"),
                    ("europe", "Europe"),
                    ("middle_east", "Middle East"),
                ],
                max_length=250,
                null=True,
            ),
        ),
    ]
