# Generated by Django 5.1.2 on 2024-10-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="fb",
            field=models.URLField(default="#", max_length=300),
        ),
        migrations.AlterField(
            model_name="contact",
            name="fb_group",
            field=models.URLField(default="#", max_length=300),
        ),
        migrations.AlterField(
            model_name="contact",
            name="linkedin",
            field=models.URLField(default="#", max_length=300),
        ),
        migrations.AlterField(
            model_name="contact",
            name="location",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="contact",
            name="whatsAppLink",
            field=models.URLField(default="#", max_length=300),
        ),
        migrations.AlterField(
            model_name="contact",
            name="x",
            field=models.URLField(default="#", max_length=300),
        ),
        migrations.AlterField(
            model_name="contact",
            name="youtube",
            field=models.URLField(default="#", max_length=300),
        ),
    ]
