# Generated by Django 5.1.2 on 2024-10-23 17:13

import django.core.validators
import utils.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_contact_fb_alter_contact_fb_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="details2",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.FileField(
                null=True,
                upload_to="general/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    utils.validator.validate_file_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="side_Img2",
            field=models.FileField(
                null=True,
                upload_to="general/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    utils.validator.validate_file_size,
                ],
            ),
        ),
    ]
