# Generated by Django 5.1.2 on 2024-10-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_service_details2_service_image_service_side_img2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="details",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="service",
            name="details2",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
