# Generated by Django 5.1.2 on 2024-10-23 17:23

import django.core.validators
import utils.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_service_details_alter_service_details2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="details2",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="general/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    utils.validator.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="side_Img2",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="general/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    utils.validator.validate_file_size,
                ],
            ),
        ),
    ]
