# Generated by Django 5.1.2 on 2024-10-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_service_details2_alter_service_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="details",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="service",
            name="details2",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
