# Generated by Django 5.1.2 on 2024-10-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_service_details_alter_service_details2"),
    ]

    operations = [
        migrations.AddField(
            model_name="serve",
            name="carousel",
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serve",
            name="options",
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
