# Generated by Django 5.1.2 on 2024-10-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_serve_carousel_serve_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serve",
            name="details",
            field=models.TextField(max_length=2000),
        ),
    ]
