# Generated by Django 5.1.2 on 2024-10-24 17:37

import django.core.validators
import utils.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_serve_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("text", models.TextField(max_length=500)),
                (
                    "photo",
                    models.FileField(
                        upload_to="general/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            ),
                            utils.validator.validate_file_size,
                        ],
                    ),
                ),
                ("phone", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=250)),
            ],
        ),
    ]
