# Generated by Django 5.1.2 on 2024-10-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="location",
            field=models.TextField(max_length=250),
        ),
    ]
