# Generated by Django 5.1.2 on 2024-10-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_contact_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="phone",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="text",
            field=models.TextField(max_length=1000),
        ),
    ]
