# Generated by Django 5.1.2 on 2024-10-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_team_phone_alter_team_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="termsAndCondition",
            field=models.TextField(default=1, max_length=50000),
            preserve_default=False,
        ),
    ]
