# Generated by Django 5.1.2 on 2024-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_setting_termsandcondition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="termsAndCondition",
            field=models.TextField(max_length=500000),
        ),
    ]
