# Generated by Django 5.1.1 on 2024-10-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userprofile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="expected_salary",
            field=models.CharField(max_length=200),
        ),
    ]
