# Generated by Django 5.1.1 on 2024-10-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_userprofile_expected_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="img",
            field=models.FileField(default=1, upload_to="general/"),
            preserve_default=False,
        ),
    ]
