# Generated by Django 5.1.1 on 2024-09-15 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posted", models.DateField(auto_created=True, auto_now_add=True)),
                ("title", models.CharField(max_length=250)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "full_time"),
                            ("part_time", "part_time"),
                            ("remote", "remote"),
                        ],
                        default="full_time",
                        max_length=250,
                    ),
                ),
                ("city", models.CharField(max_length=250)),
                ("state", models.CharField(max_length=250)),
                (
                    "experience",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("zip_code", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=500)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="country.country",
                    ),
                ),
            ],
        ),
    ]
