# Generated by Django 5.1.1 on 2024-10-13 17:07

import django.core.validators
import django.db.models.deletion
import utils.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("companyName", models.CharField(max_length=250)),
                ("position", models.CharField(max_length=250)),
                ("requirement", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Grievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("title", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=250)),
                ("remarks", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("age", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=250)),
                ("position", models.CharField(max_length=250)),
                ("ielts", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("whatsApp", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CIVIL", "Civil"),
                            ("MECHANICAL", "Mechanical"),
                            ("ELECTRIAL", "Electrial"),
                            ("IT", "It"),
                            ("INSTRUMENTATION", "Instrumentation"),
                            ("ADMIN", "Admin/HR"),
                            ("SAFETY", "Safety"),
                            ("STAFF", "Project/Planning/Staff"),
                            ("DESIGN", "Design"),
                            ("HEALTHCARE", "Healthcare"),
                            ("HOSPITALITY", "Hospitality"),
                            ("SECURITY", "Security"),
                            ("LOGISTICS", "Logistics"),
                            ("OPERATORS", "Operators/Drivers"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=250,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("SOFTWARE ENGINEER", "Software Engineer"),
                            ("DATA SCIENTIST", "Data Scientist"),
                            ("PRODUCT MANAGER", "Product Manager"),
                            ("DIGITAL MARKETING MANAGER", "Digital Marketing Manager"),
                            ("CLOUD ENGINEER", "Cloud Engineer"),
                            ("CYBERSECURITY ANALYST", "Cybersecurity Analyst"),
                            ("UX/UI DESIGNER", "UX/UI Designer"),
                            ("AI/ML ENGINEER", "AI/ML Engineer"),
                            ("DEVOPS ENGINEER", "DevOps Engineer"),
                            ("BUSINESS ANALYST", "Business Analyst"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        upload_to="resumes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            ),
                            utils.validator.validate_file_size,
                        ],
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candition_location",
                        to="country.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posted", models.DateField(auto_created=True, auto_now_add=True)),
                ("title", models.CharField(max_length=250)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "full_time"),
                            ("part_time", "part_time"),
                            ("remote", "remote"),
                        ],
                        default="full_time",
                        max_length=250,
                    ),
                ),
                ("city", models.CharField(max_length=250)),
                ("state", models.CharField(max_length=250)),
                (
                    "experience",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("zip_code", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=500)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="country.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplyJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("designation", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("age", models.CharField(max_length=15)),
                ("skills", models.TextField(max_length=250)),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resumes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            ),
                            utils.validator.validate_file_size,
                        ],
                    ),
                ),
                (
                    "coverLetter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="coverLetters/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            ),
                            utils.validator.validate_file_size,
                        ],
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apply_job",
                        to="job.job",
                    ),
                ),
            ],
        ),
    ]
