# Generated by Django 5.1.2 on 2024-10-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CIVIL", "Civil"),
                    ("MECHANICAL", "Mechanical"),
                    ("ELECTRIAL", "Electrial"),
                    ("IT", "It"),
                    ("INSTRUMENTATION", "Instrumentation"),
                    ("ADMIN", "Admin/HR"),
                    ("SAFETY", "Safety"),
                    ("STAFF", "Project/Planning/Staff"),
                    ("DESIGN", "Design"),
                    ("HEALTHCARE", "Healthcare"),
                    ("HOSPITALITY", "Hospitality"),
                    ("SECURITY", "Security"),
                    ("LOGISTICS", "Logistics"),
                    ("OPERATORS", "Operators/Drivers"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=250,
                null=True,
            ),
        ),
    ]
