# Generated by Django 5.1.1 on 2024-09-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplyJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.EmailField(max_length=250)),
                ("designation", models.EmailField(max_length=15)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.EmailField(max_length=15)),
                ("age", models.DecimalField(decimal_places=2, max_digits=2)),
                ("skills", models.EmailField(max_length=250)),
                ("resume", models.FileField(upload_to="resumes/")),
                ("coverLetter", models.FileField(upload_to="coverLetters/")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apply_job",
                        to="job.job",
                    ),
                ),
            ],
        ),
    ]
