# Generated by Django 5.1.1 on 2024-09-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_applyjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyjob",
            name="name",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="applyjob",
            name="phone",
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name="applyjob",
            name="skills",
            field=models.TextField(max_length=500),
        ),
    ]
