# Generated by Django 5.1.1 on 2024-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_applyjob_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyjob",
            name="designation",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="applyjob",
            name="skills",
            field=models.TextField(max_length=450),
        ),
    ]
