# Generated by Django 5.1.2 on 2024-10-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "__first__"),
        ("job", "0002_alter_candidate_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candition_location",
                to="country.country",
            ),
        ),
    ]
