# Generated by Django 5.1.1 on 2024-09-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_alter_applyjob_name_alter_applyjob_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyjob",
            name="designation",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="applyjob",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="applyjob",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="applyjob",
            name="skills",
            field=models.TextField(max_length=250),
        ),
    ]
