# Generated by Django 5.1.1 on 2024-09-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_alter_applyjob_designation_alter_applyjob_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyjob",
            name="age",
            field=models.CharField(max_length=15),
        ),
    ]
