# Generated by Django 5.1.1 on 2024-09-19 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0001_initial"),
        ("job", "0005_alter_applyjob_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("companyName", models.CharField(max_length=250)),
                ("position", models.CharField(max_length=250)),
                ("requirement", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("age", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=250)),
                ("position", models.CharField(max_length=250)),
                ("ielts", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsApp", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("name", models.CharField(max_length=250)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CIVIL", "Civil"),
                            ("MECHANICAL", "Mechanical"),
                            ("ELECTRIAL", "Electrial"),
                            ("IT", "It"),
                            ("INSTRUMENTATION", "Instrumentation"),
                            ("ADMIN", "Admin/HR"),
                            ("SAFETY", "Safety"),
                            ("STAFF", "Project/Planning/Staff"),
                            ("DESIGN", "Design"),
                            ("HEALTHCARE", "Healthcare"),
                            ("HOSPITALITY", "Hospitality"),
                            ("SECURITY", "Security"),
                            ("LOGISTICS", "Logistics"),
                            ("OPERATORS", "Operators/Drivers"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=250,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("SOFTWARE ENGINEER", "Software Engineer"),
                            ("DATA SCIENTIST", "Data Scientist"),
                            ("PRODUCT MANAGER", "Product Manager"),
                            ("DIGITAL MARKETING MANAGER", "Digital Marketing Manager"),
                            ("CLOUD ENGINEER", "Cloud Engineer"),
                            ("CYBERSECURITY ANALYST", "Cybersecurity Analyst"),
                            ("UX/UI DESIGNER", "UX/UI Designer"),
                            ("AI/ML ENGINEER", "AI/ML Engineer"),
                            ("DEVOPS ENGINEER", "DevOps Engineer"),
                            ("BUSINESS ANALYST", "Business Analyst"),
                        ],
                        max_length=250,
                    ),
                ),
                ("email", models.EmailField(max_length=250)),
                ("resume", models.FileField(upload_to="resumes/")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candition_location",
                        to="country.country",
                    ),
                ),
            ],
        ),
    ]
