# Generated by Django 5.1.1 on 2024-09-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_employee_study_candidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("title", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=250)),
                ("remarks", models.TextField(max_length=250)),
            ],
        ),
    ]
