# Generated by Django 5.1.2 on 2024-10-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_alter_save_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="agreed",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
