# Generated by Django 5.1.2 on 2024-10-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_candidate_agreed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("remote", "Remote"),
                ],
                default="full_time",
                max_length=250,
            ),
        ),
    ]
