# Generated by Django 5.1.2 on 2024-10-25 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0003_alter_country_continent"),
        ("job", "0009_alter_job_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="country.country",
            ),
        ),
    ]
