# Generated by Django 5.1.2 on 2024-10-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0013_alter_job_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.CharField(max_length=250),
        ),
    ]
