# Generated by Django 5.1.2 on 2024-10-25 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0015_alter_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="save",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs_save",
                to="job.job",
            ),
        ),
    ]
