# Generated by Django 5.1.2 on 2024-10-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0016_alter_save_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="ielts",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")], max_length=100
            ),
        ),
    ]
