# Generated by Django 5.1.2 on 2024-10-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0017_alter_study_ielts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="study",
            old_name="name",
            new_name="firstName",
        ),
        migrations.AddField(
            model_name="study",
            name="lastName",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
