# Generated by Django 5.1.2 on 2024-10-25 18:37

import django.core.validators
import utils.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0018_rename_name_study_firstname_study_lastname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="phone",
        ),
        migrations.AddField(
            model_name="candidate",
            name="exp",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="exp2",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    utils.validator.validate_file_size,
                ],
            ),
        ),
    ]
