# Generated by Django 5.1.2 on 2024-10-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0019_remove_candidate_phone_candidate_exp_candidate_exp2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="phone",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
