# Generated by Django 5.1.2 on 2024-10-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0020_candidate_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=250)),
                ("last", models.CharField(max_length=250)),
                ("phone", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.EmailField(blank=True, max_length=250, null=True)),
                (
                    "companyName",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=250, null=True)),
                ("comment", models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
